### ISSUE TITLE
Bones are placed in the void

### ISSUE THREAD

**Issue by Niklp09** [OgelGames/bones#6]
On my server, a player died just below the world boundary and the bones were spawned on a coordinate that is no longer accessible by players. (-21744,30928,-23035). Since the bones were invisible I pulled them back into the normal world with a mesecons pistons. Conclusion: bones should only be spawned within the "visible" world.

**Comment by OgelGames** [comment]
Hmm... that shouldn't be possible, there is a check for ignore nodes (which is what the "void" should be):
https://github.com/OgelGames/bones/blob/16443978817f020ffffbb25025e0aa45c3dfcee5/death.lua#L14-L16

**Comment by Niklp09** [comment]
`//lua local node = minetest.get_node(vector.new(-21744,30928,-23035)) print(node.name)`
results in `air`
everything from +30929 is ignore
I have tested manually, +30927 is the last position visible for players
`//lua minetest.set_node(vector.new(-21744,30928,-23035), {name = "default:dirt"})`

**Comment by OgelGames** [comment]
That seems like a engine bug to me 🤔

**Comment by SwissalpS** [comment]
> `//lua local node = minetest.get_node(vector.new(-21744,30928,-23035)) print(node.name)` results in `air` everything from +30929 is ignore I have tested manually, +30927 is the last position visible for players `//lua minetest.set_node(vector.new(-21744,30928,-23035), {name = "default:dirt"})`

I tested at -30912 -30913 -30912, placing the node there this way results in nothing visible but checking with core.get_node returns 'default:dirt'.

The limit in negative direction is -30912 but only when default chunk size is used.
According to Huhhila: "Center of an axis is at 7.5 instead of 0.0 if considering just the mapgen'd non-ignore space.
Coordinates are +/- 386 mapchunks from that... in other words from  -386 * 80 - 32 to +386 * 80 + 47"

The whole thing gets more complicated since mapchunks can be different size than 80!
Though, how many servers actually do that?
https://github.com/luanti-org/luanti/blob/master/src/settings_translation_file.cpp#L1135
does highly discourage from changing chunksize.
